from flask_uploads import UploadSet
import json


with open('variables.json') as file:
    data = json.load(file)
MAX_CONTENT_LENGTH_BYTES = data["MAX_CONTENT_LENGTH_BYTES"]
ALLOWED_EXTENSIONS_PHOTOS = tuple(data["ALLOWED_EXTENSIONS_PHOTOS"])
ALLOWED_EXTENSIONS_FILES = tuple(data["ALLOWED_EXTENSIONS_FILES"])
UPLOAD_FOLDER = data["UPLOAD_FOLDER"]
UPLOAD_FOLDER_PHOTOS = data["UPLOAD_FOLDER_PHOTOS"]
UPLOAD_FOLDER_FILES = data["UPLOAD_FOLDER_FILES"]
MAX_FILES_COUNT = data["MAX_FILES_COUNT"]
photos = UploadSet(UPLOAD_FOLDER_PHOTOS, ALLOWED_EXTENSIONS_PHOTOS)
files = UploadSet(UPLOAD_FOLDER_FILES, ALLOWED_EXTENSIONS_FILES)
